// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7MoTCcXAsYDcvB7Rabaa2vM99mpMn4o0',
    appId: '1:229842654270:web:8995322f51e5b138bf6d6f',
    messagingSenderId: '229842654270',
    projectId: 'samiocare-acf22',
    authDomain: 'samiocare-acf22.firebaseapp.com',
    storageBucket: 'samiocare-acf22.firebasestorage.app',
    measurementId: 'G-Q2KCXKXRYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDck-dFmaUYu9VDr_ekyrOy3Ik0-GiNHbw',
    appId: '1:229842654270:android:35ab86bf7fd197e4bf6d6f',
    messagingSenderId: '229842654270',
    projectId: 'samiocare-acf22',
    storageBucket: 'samiocare-acf22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAxvBe2Ac0uVcg6k9W1pjB2cHy02wzkMo',
    appId: '1:229842654270:ios:af368d4f29c2f7d4bf6d6f',
    messagingSenderId: '229842654270',
    projectId: 'samiocare-acf22',
    storageBucket: 'samiocare-acf22.firebasestorage.app',
    iosBundleId: 'com.example.samiocareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAxvBe2Ac0uVcg6k9W1pjB2cHy02wzkMo',
    appId: '1:229842654270:ios:af368d4f29c2f7d4bf6d6f',
    messagingSenderId: '229842654270',
    projectId: 'samiocare-acf22',
    storageBucket: 'samiocare-acf22.firebasestorage.app',
    iosBundleId: 'com.example.samiocareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7MoTCcXAsYDcvB7Rabaa2vM99mpMn4o0',
    appId: '1:229842654270:web:c15f39cb5604cb2abf6d6f',
    messagingSenderId: '229842654270',
    projectId: 'samiocare-acf22',
    authDomain: 'samiocare-acf22.firebaseapp.com',
    storageBucket: 'samiocare-acf22.firebasestorage.app',
    measurementId: 'G-M4P7ZKW38L',
  );
}
